name: Docker Compose CI

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version

    - name: Build and push Docker images
      run: | 
        cp -n .env.example .env
        docker-compose up -d --build

    - name: Build and push Docker images
      run: |
        docker ps
        sleep 30
        docker-compose exec -T php chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache
        docker-compose exec -T php chmod -R 775 /var/www/storage /var/www/bootstrap/cache
        docker-compose exec -T php artisan down
        docker-compose exec -T php composer setup
        docker-compose exec -T php artisan up
        docker-compose exec -T phpmyadmin chmod 777 /sessions

    - name: Published on github pages
      uses: actions/configure-pages@v5

    - name: Published on github pages
      uses: actions/upload-pages-artifact@v3